include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - camel_case_types
    - avoid_print

analyzer:
  errors:
    todo: ignore
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/l10n/*.dart