version: '3.3'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy:0.6.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  synapse:
    image: matrixdotorg/synapse:v1.45.1
    restart: always
    expose:
      - "8008"
    volumes:
      - ./synapse-data:/data
    environment:
      VIRTUAL_HOST: NOMBREDEDOMINIO.COM
      VIRTUAL_PORT: 8008
      LETSENCRYPT_HOST: NOMBREDEDOMINIO.COM
      LETSENCRYPT_EMAIL: soporte@NOMBREDEDOMINIO.COM

  postgres:
    image: 'postgres:9.6.21'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=***
    ports:
      - '5432:5432'

  mautrix-telegram:
      container_name: mautrix-telegram
      image: dock.mau.dev/tulir/mautrix-telegram:latest
      restart: unless-stopped
      ports:
      - "29317:29317"
      volumes:
      - .:/data


volumes:
  certs:
  confd:
  vhostd:
  html:
