name: fluffychat
description: Chat with your friends.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.19.1+46

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  famedlysdk:
    git:
      url: https://gitlab.com/famedly/famedlysdk.git
      ref: 74bd1d331b77f45ab0793af7c9e607795b8c16f0

  localstorage: ^3.0.1+4
  file_picker_cross: ^4.2.2
  image_picker: ^0.6.7+11
  url_launcher: ^5.7.2
  cached_network_image: ^2.3.2+1
  firebase_messaging: ^7.0.2
  flutter_local_notifications: ^1.4.3
  matrix_link_text: ^0.1.5
  path_provider: ^1.5.1
  webview_flutter: ^0.3.19+9
  share: ^0.6.3+5
  flutter_secure_storage: ^3.3.4
  http: ^0.12.0+4
  universal_html: ^1.1.12
  receive_sharing_intent: ^1.3.3
  flutter_slidable: ^0.5.4
  photo_view: ^0.10.2
  flutter_sound: ^2.1.1
  open_file: ^3.0.1
  mime_type: ^0.3.0
  bot_toast: ^3.0.0
  flutter_matrix_html: ^0.1.7
  moor: ^3.3.1
  sqlite3_flutter_libs: ^0.2.0
  sqlite3: ^0.1.4
  random_string: ^2.0.1
  flutter_typeahead: ^1.8.1
  flutter_olm: ^1.0.1
  intl: ^0.16.1
  intl_translation: ^0.17.9
  flutter_localizations:
    sdk: flutter
  sqflite: ^1.1.7 # Still used to obtain the database location
  native_imaging:
    git:
      url: https://gitlab.com/famedly/libraries/native_imaging.git
      ref: master
  flutter_blurhash: ^0.5.0
  sentry: ">=3.0.0 <4.0.0"
  scroll_to_index: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.4"
  pedantic: ^1.9.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # Adds code generation (synthetic package) support
  generate: true


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/sounds/
    - assets/js/
    - assets/js/package/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
